apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: v1-1-acc-registry-app
  namespace: acc-app-hilversum
  labels:
    app: registry-app
    release: "v1-1-acc"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry-app
        release: "v1-1-acc"
    spec:
      nodeSelector:
        environment: acceptance
      containers:
        - name: v1-1-acc-registry-app
          image: daasdtr01.dtr:5000/mycity/registry-app-acc:1.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80